SET(LIB_REQUIRED_DEP_PACKAGES
  Teuchos Epetra EpetraExt Amesos AztecOO Ifpack ML Anasazi Belos NOX)
SET(LIB_OPTIONAL_DEP_PACKAGES)

SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)

SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS MPI)

SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS MPI)

