# CMake generated Testfile for 
# Source directory: /home/aditya/quinoa/regression/inciter/cfl
# Build directory: /home/aditya/quinoa/cmake/regression/inciter/cfl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(inciter:cfl_pe1 "/usr/bin/cmake" "-DTEST_NAME=inciter:cfl_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/inciter/cfl/inciter:cfl_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/inciter" "-DTEST_EXECUTABLE_ARGS=-c slot_cyl_cfl.q -i unitsquare_01_3.6k.exo -v" "-DTEST_LABELS=LABELS inciter" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=slot_cyl_cfl_pe1_u0.0.std.exo" "-DBIN_RESULT=out.0" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(inciter:cfl_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "inciter" PASS_REGULAR_EXPRESSION ".*inciter:cfl_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/inciter/cfl/inciter:cfl_pe1")
add_test(inciter:cfl_pe4 "/usr/bin/cmake" "-DTEST_NAME=inciter:cfl_pe4" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/inciter/cfl/inciter:cfl_pe4" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/inciter" "-DTEST_EXECUTABLE_ARGS=-c slot_cyl_cfl.q -i unitcube_01_31k.exo -v" "-DTEST_LABELS=LABELS inciter" "-DNUMPES=4" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=-m" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=slot_cyl_cfl_pe4_u0.0.std.exo.0 slot_cyl_cfl_pe4_u0.0.std.exo.1 slot_cyl_cfl_pe4_u0.0.std.exo.2 slot_cyl_cfl_pe4_u0.0.std.exo.3" "-DBIN_RESULT=out.0 out.1 out.2 out.3" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(inciter:cfl_pe4 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "inciter" PASS_REGULAR_EXPRESSION ".*inciter:cfl_pe4.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "4" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/inciter/cfl/inciter:cfl_pe4")
add_test(inciter:cfl_u0.7_pe1 "/usr/bin/cmake" "-DTEST_NAME=inciter:cfl_u0.7_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/inciter/cfl/inciter:cfl_u0.7_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/inciter" "-DTEST_EXECUTABLE_ARGS=-c slot_cyl_cfl.q -i unitsquare_01_3.6k.exo -v -u 0.7" "-DTEST_LABELS=LABELS inciter" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=-m" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=slot_cyl_cfl_pe1_u0.7.std.exo.0 slot_cyl_cfl_pe1_u0.7.std.exo.1" "-DBIN_RESULT=out.0 out.1" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(inciter:cfl_u0.7_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "inciter" PASS_REGULAR_EXPRESSION ".*inciter:cfl_u0.7_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/inciter/cfl/inciter:cfl_u0.7_pe1")
