# CMake generated Testfile for 
# Source directory: /home/aditya/quinoa/regression/meshconv/exo_output
# Build directory: /home/aditya/quinoa/cmake/regression/meshconv/exo_output
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(meshconv:netgen2exo_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:netgen2exo_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:netgen2exo_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i box_24.mesh -o box_24.exo -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=box_24.exo.std" "-DBIN_RESULT=box_24.exo" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:netgen2exo_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:netgen2exo_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:netgen2exo_pe1")
add_test(meshconv:gmshtxt2exo_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:gmshtxt2exo_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:gmshtxt2exo_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i box_24.txt.msh -o box_24.exo -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=box_24.exo.std" "-DBIN_RESULT=box_24.exo" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:gmshtxt2exo_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:gmshtxt2exo_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:gmshtxt2exo_pe1")
add_test(meshconv:gmshbin2exo_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:gmshbin2exo_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:gmshbin2exo_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i box_24.msh -o box_24.exo -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=box_24.exo.std" "-DBIN_RESULT=box_24.exo" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:gmshbin2exo_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:gmshbin2exo_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:gmshbin2exo_pe1")
add_test(meshconv:multiblockexo2exo_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:multiblockexo2exo_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:multiblockexo2exo_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i shear_5blocks.exo -o shear.exo -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=exodiff.cfg" "-DBIN_BASELINE=shear.exo.std" "-DBIN_RESULT=shear.exo" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:multiblockexo2exo_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:multiblockexo2exo_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/exo_output/meshconv:multiblockexo2exo_pe1")
