SET(LIB_REQUIRED_DEP_PACKAGES
  Teuchos Epetra EpetraExt Amesos AztecOO Ifpack ML Anasazi Belos NOX Intrepid)
SET(LIB_OPTIONAL_DEP_PACKAGES SEACASExodus Stokhos)

SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)

SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS Peano MPI Netcdf)

SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS Peano MPI Netcdf)

