#!/bin/sh -ex
RUNNER_NCPUS_ARG=$1
NUMPES=$2
TEST_EXECUTABLE=$3
shift 3
TEST_EXECUTABLE_ARGS="$@"
runjob --block $COBALT_PARTNAME $RUNNER_NCPUS_ARG $NUMPES --ranks-per-node 16 --verbose 2 : $TEST_EXECUTABLE $TEST_EXECUTABLE_ARGS
