# CMake generated Testfile for 
# Source directory: /home/aditya/quinoa/regression/rngtest
# Build directory: /home/aditya/quinoa/cmake/regression/rngtest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rngtest:SmallCrush_all_rngsse_pe8 "/usr/bin/cmake" "-DTEST_NAME=rngtest:SmallCrush_all_rngsse_pe8" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/rngtest/rngtest:SmallCrush_all_rngsse_pe8" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/rngtest" "-DTEST_EXECUTABLE_ARGS=-c SmallCrush_all_rngsse.q -v" "-DTEST_LABELS=LABELS rngtest stringent" "-DNUMPES=8" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(rngtest:SmallCrush_all_rngsse_pe8 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "rngtest;stringent" PASS_REGULAR_EXPRESSION ".*rngtest:SmallCrush_all_rngsse_pe8.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "8" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/rngtest/rngtest:SmallCrush_all_rngsse_pe8")
add_test(rngtest:BigCrush_r123_philox_pe4 "/usr/bin/cmake" "-DTEST_NAME=rngtest:BigCrush_r123_philox_pe4" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/rngtest/rngtest:BigCrush_r123_philox_pe4" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/rngtest" "-DTEST_EXECUTABLE_ARGS=-c BigCrush_r123_philox.q -v" "-DTEST_LABELS=LABELS rngtest extreme stringent" "-DNUMPES=4" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(rngtest:BigCrush_r123_philox_pe4 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "rngtest;extreme;stringent" PASS_REGULAR_EXPRESSION ".*rngtest:BigCrush_r123_philox_pe4.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "4" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/rngtest/rngtest:BigCrush_r123_philox_pe4")
add_test(rngtest:SmallCrush_all_r123_pe8 "/usr/bin/cmake" "-DTEST_NAME=rngtest:SmallCrush_all_r123_pe8" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/rngtest/rngtest:SmallCrush_all_r123_pe8" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/rngtest" "-DTEST_EXECUTABLE_ARGS=-c SmallCrush_all_r123.q -v" "-DTEST_LABELS=LABELS rngtest" "-DNUMPES=8" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(rngtest:SmallCrush_all_r123_pe8 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "rngtest" PASS_REGULAR_EXPRESSION ".*rngtest:SmallCrush_all_r123_pe8.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "8" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/rngtest/rngtest:SmallCrush_all_r123_pe8")
add_test(rngtest:Crush_r123_threefry_pe4 "/usr/bin/cmake" "-DTEST_NAME=rngtest:Crush_r123_threefry_pe4" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/rngtest/rngtest:Crush_r123_threefry_pe4" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/rngtest" "-DTEST_EXECUTABLE_ARGS=-c Crush_r123_threefry.q -v" "-DTEST_LABELS=LABELS rngtest extreme stringent" "-DNUMPES=4" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=" "-DTEXT_BASELINE=" "-DTEXT_RESULT=" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=" "-DPOSTPROCESS_PROG_ARGS=" "-DPOSTPROCESS_PROG_OUTPUT=" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(rngtest:Crush_r123_threefry_pe4 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "rngtest;extreme;stringent" PASS_REGULAR_EXPRESSION ".*rngtest:Crush_r123_threefry_pe4.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "4" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/rngtest/rngtest:Crush_r123_threefry_pe4")
