if(__addCharmModule)
  return()
endif()
set(__addCharmModule YES)

# Function 'addCharmModule' is used to add custom build commands and dependency
# for a Charm++ module
function(addCharmModule SRCPATH MODULE HOSTFILE PARTOF)
# Arguments:
#   SRCPATH:  Path where the .ci Charm++ module file resides, relative to
#             CMAKE_SOURCE_DIR.
#   MODULE:   Name of the Charm++ module.
#   HOSTFILE: Name of the .C file that includes the Charm++-generated .decl.h
#             and .def.h.
#   PARTOF:   Name of the library or executable the Charm++ module (and the
#             Charm++ host file) will link to. Note that the library or
#             executable PARTOF requires a custom link command as that must be
#             linked by the charmc wrapper, which is generated by the cmake
#             function addCharmLibrary or addCharmExecutable, respectively.

  # Add custom command generating .decl.h and .def.h from .ci
  add_custom_command(OUTPUT ${MODULE}.decl.h ${MODULE}.def.h
                     DEPENDS ${CMAKE_SOURCE_DIR}/${SRCPATH}/${MODULE}.ci
                     COMMAND ${CHARM_COMPILER}
                             ${CMAKE_SOURCE_DIR}/${SRCPATH}/${MODULE}.ci)
  add_custom_target(${MODULE}CharmModule
                    DEPENDS ${MODULE}.decl.h ${MODULE}.def.h)
  add_dependencies(${PARTOF} ${MODULE}CharmModule)

  # Add (current) binary directory, i.e., which this function was called from,
  # to list of include directories as .decl.h and .def.h will be generated there
  include_directories(${PROJECT_BINARY_DIR})

  # Ignore some warnings for HOSTFILE that includes the Charm-generated .decl.h
  # and .def.h
  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")  # intel-specific ignores
    # Suppress the following Intel compiler warnings/remarks:
    #  177: variable was declared but never referenced
    #  181: argument of type "unsigned char *" is incompatible with format
    #       "%c", expecting argument of type "char *"
    # 1572: floating-point equality and inequality comparisons are unreliable
    # 1599: declaration hides variable
    # 1720: function "<class>::operator new" has no corresponding member
    #       operator delete (to be called if an exception is thrown during
    #       initialization of an allocated object)
    # 1944: declaration shadows a member of 'this'
    # 2259: non-pointer conversion from "int" to "unsigned char" may lose
    #       significant bits
    # 3280: declaration hides member
    set(HOSTFILE_FLAGS "-diag-disable 177,181,1572,1599,1720,1944,2259,3280")
  else()
    set(HOSTFILE_FLAGS "-Wno-shadow -Wno-unused-variable -Wno-unused-parameter -Wno-deprecated-register -Wno-mismatched-tags -Wno-cast-align")
  endif()
  set_property(SOURCE ${HOSTFILE} APPEND_STRING PROPERTY COMPILE_FLAGS
               ${HOSTFILE_FLAGS})

#  # Build list of compiler arguments with each include directory, -I..., -I...
#  get_property(include_dirs DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
#               PROPERTY INCLUDE_DIRECTORIES)
#  set(INCDIR_FLAGS "")
#  foreach(dir ${include_dirs})
#    LIST(APPEND INCDIR_FLAGS "-I${dir}")
#  endforeach()
#
#  # Add custom command compiling the Charm++ host file using the charmc wrapper
#  add_custom_command(OUTPUT ${CMAKE_SOURCE_DIR}/${SRCPATH}/${HOSTFILE}.o
#                     DEPENDS ${CMAKE_SOURCE_DIR}/${SRCPATH}/${HOSTFILE}.C)
#                     COMMAND ${CMAKE_CXX_COMPILER}
#                             ${CMAKE_CXX_FLAGS}
#                             ${CXXFLAGS}
#                             ${HOSTFILE_FLAGS}
#                             ${CMAKE_SHARED_MODULE_CXX_FLAGS}
#                             ${INCDIR_FLAGS}
#                             -o ${CMAKE_SOURCE_DIR}/${SRCPATH}/${HOSTFILE}.o
#                             -c ${CMAKE_SOURCE_DIR}/${SRCPATH}/${HOSTFILE}.C)
#  add_custom_target([CharmHost]${HOSTFILE}.o
#                    DEPENDS ${CMAKE_SOURCE_DIR}/${SRCPATH}/${HOSTFILE}.o
#                            ${MODULE}CharmModule)
#  add_dependencies(${PARTOF} [CharmHost]${HOSTFILE}.o)
#  set_target_properties([CharmHost]${HOSTFILE}.o PROPERTIES RULE_LAUNCH_COMPILE
#                        "${CHARM_COMPILER}")

  # Echo status on adding Charm++ module
  message(STATUS "Add Charm++ module ${MODULE}.ci in ${HOSTFILE} at ${CMAKE_SOURCE_DIR}/${SRCPATH}/ linking to ${PARTOF}")
  message(STATUS "  Extra ${HOSTFILE} compiler flags: ${HOSTFILE_FLAGS}")

endfunction(addCharmModule)


function(addCharmExecutable TARGET)

  set_target_properties(${TARGET} PROPERTIES RULE_LAUNCH_LINK
                        "${CHARM_COMPILER}")

#  message(STATUS "=== ${RULE_LAUNCH_LINK}")
#  get_property(objects SOURCE ${TARGET} PROPERTY LINK_LIBRARIESD)
#  foreach(obj ${objects})
#    message(STATUS "obj: ${obj}")
#  endforeach()
#
#  message(STATUS ${MPI_LINK_FLAGS})
#  message(STATUS "===")

endfunction(addCharmExecutable)
