# CMake generated Testfile for 
# Source directory: /home/aditya/quinoa/regression/meshconv/gmsh_output
# Build directory: /home/aditya/quinoa/cmake/regression/meshconv/gmsh_output
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(meshconv:exo2gmsh_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:exo2gmsh_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/gmsh_output/meshconv:exo2gmsh_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i box_24.exo -o box_24.msh -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=gmsh.ndiff.cfg" "-DTEXT_BASELINE=gmsh-check_box_24.txt.std" "-DTEXT_RESULT=gmsh-check.txt" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=/usr/bin/gmsh" "-DPOSTPROCESS_PROG_ARGS=-check box_24.msh COMMAND grep -v binary COMMAND grep -v dense" "-DPOSTPROCESS_PROG_OUTPUT=gmsh-check.txt" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:exo2gmsh_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:exo2gmsh_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/gmsh_output/meshconv:exo2gmsh_pe1")
add_test(meshconv:gmshtxt2gmsh_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:gmshtxt2gmsh_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/gmsh_output/meshconv:gmshtxt2gmsh_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i box_24.txt.msh -o box_24.msh -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=gmsh.ndiff.cfg" "-DTEXT_BASELINE=gmsh-check_box_24.txt.std" "-DTEXT_RESULT=gmsh-check.txt" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=/usr/bin/gmsh" "-DPOSTPROCESS_PROG_ARGS=-check box_24.msh COMMAND grep -v binary COMMAND grep -v dense" "-DPOSTPROCESS_PROG_OUTPUT=gmsh-check.txt" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:gmshtxt2gmsh_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:gmshtxt2gmsh_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/gmsh_output/meshconv:gmshtxt2gmsh_pe1")
add_test(meshconv:netgen2gmsh_pe1 "/usr/bin/cmake" "-DTEST_NAME=meshconv:netgen2gmsh_pe1" "-DWORKDIR=/home/aditya/quinoa/cmake/regression/meshconv/gmsh_output/meshconv:netgen2gmsh_pe1" "-DRUNNER=/home/aditya/quinoa/cmake/charmrun" "-DRUNNER_NCPUS_ARG=+p" "-DRUNNER_ARGS=--bind-to none --map-by node" "-DTEST_EXECUTABLE=/home/aditya/quinoa/cmake/Main/meshconv" "-DTEST_EXECUTABLE_ARGS=-i torus.mesh -o torus.msh -v" "-DTEST_LABELS=LABELS meshconv" "-DNUMPES=1" "-DTEXT_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/maddiff" "-DTEXT_DIFF_PROG_ARGS=" "-DTEXT_DIFF_PROG_CONF=gmsh.ndiff.cfg" "-DTEXT_BASELINE=gmsh-check_torus.txt.std" "-DTEXT_RESULT=gmsh-check.txt" "-DBIN_DIFF_PROG=/home/aditya/quinoa/tpl/install/gnu-x86_64/bin/exodiff" "-DBIN_DIFF_PROG_ARGS=" "-DBIN_DIFF_PROG_CONF=" "-DBIN_BASELINE=" "-DBIN_RESULT=" "-DPOSTPROCESS_PROG=/usr/bin/gmsh" "-DPOSTPROCESS_PROG_ARGS=-check torus.msh COMMAND grep -v binary COMMAND grep -v dense" "-DPOSTPROCESS_PROG_OUTPUT=gmsh-check.txt" "-P" "/home/aditya/quinoa/src/../cmake/test_runner.cmake")
set_tests_properties(meshconv:netgen2gmsh_pe1 PROPERTIES  FAIL_REGULAR_EXPRESSION "exodiff: ERROR;exodiff: Files are different" LABELS "meshconv" PASS_REGULAR_EXPRESSION ".*meshconv:netgen2gmsh_pe1.*PASS;Failed statistics;All tests passed;exodiff: Files are the same;would be required for this test to be rigorous" PROCESSORS "1" WORKING_DIRECTORY "/home/aditya/quinoa/cmake/regression/meshconv/gmsh_output/meshconv:netgen2gmsh_pe1")
